version: '3.9'
services:
  mongodb_container:
    container_name: mongo_reastr
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: auth
    ports:
      - 27017:27017
    volumes:
      - ./docker-entrypoint-init.d/mongo_init.js:/docker-entrypoint-init.d/mongo_init.js:ro
      - ./mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
